# Generated by Django 4.1.5 on 2023-03-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(blank=True, max_length=6, null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateField(blank=True)),
                ('valor', models.CharField(blank=True, max_length=10, null=True)),
                ('movimento', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
