# Generated by Django 4.1.5 on 2023-03-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='os',
            new_name='obs',
        ),
    ]
