# Generated by Django 4.1.5 on 2023-04-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_os_finance_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
