# Generated by Django 4.1.5 on 2023-04-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_finance_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
