# Generated by Django 4.1.5 on 2023-04-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_finance_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='tipo_pgto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
